language: csharp
solution: SimpleCAP.sln
mono: none
dist: xenial
os: linux
dotnet: 3.1
install:
 - dotnet restore
script:
 - dotnet build --configuration Release
 - dotnet nuget push SimpleCAP/bin/Release/*.nupkg -s "https://nuget.org" -k $NUGET_API_KEY --skip-duplicate